### ISSUE TITLE
NoSuchElementException: Returned node was not a DOM element

### ISSUE THREAD

**Issue by suziying** [SeleniumHQ/htmlunit-driver#32] opened 2016-12-23 06:48 UTC
It's wired that when i try to use htmluniter driver to click element. My code is below:
```java
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.htmlunit.HtmlUnitDriver;

public class HtmlUnitDriverTest {
	
	@Test()
	public void testUnitDriver() throws InterruptedException {
		WebDriver driver = new HtmlUnitDriver();
		driver.navigate().to("http://x.x.x.x/#/home");
		driver.findElement(By.cssSelector("header.header--desktop.hidden-xs-down > div > div > div > a")).click();
	}
}
```
And i got below errors:
```
org.openqa.selenium.NoSuchElementException: Returned node was not a DOM element
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.52.0', revision: '4c2593cfc3689a7fcd7be52549167e5ccc93ad28', time: '2016-02-11 11:22:43'
System info: host: 'William-MacBook-Pro.local', ip: 'x.x.x.117', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.2', java.version: '1.8.0_111'
Driver info: driver.version: HtmlUnitDriver
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElementByCssSelector(HtmlUnitDriver.java:1060)
	at org.openqa.selenium.By$ByCssSelector.findElement(By.java:430)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver$5.call(HtmlUnitDriver.java:1725)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver$5.call(HtmlUnitDriver.java:1721)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.implicitlyWaitFor(HtmlUnitDriver.java:1367)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElement(HtmlUnitDriver.java:1721)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElement(HtmlUnitDriver.java:606)
	at HtmlUnitDriver.test.HtmlUnitDriverTest.testUnitDriver(HtmlUnitDriverTest.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by asashour** [comment] 2016-12-23 08:36
Please provide the URL, so others can investigate the error.

**Comment by suziying** [comment] 2016-12-25 22:20
http://10.0.1.26/#/home

**Comment by asashour** [comment] 2016-12-26 04:39
This is a local network address, which no one else can access.

**Comment by suziying** [comment] 2016-12-26 22:30
You can try this one:
www.airwallex.com

Thanks

**Comment by asashour** [comment] 2016-12-27 08:25
There is an error:

```
Caused by: net.sourceforge.htmlunit.corejs.javascript.EcmaError: ReferenceError: "selfUpdatingLiveRates" is not defined. (https://www.airwallex.com/airwallex.js?3be306dad8eb5eda5b4e&ac491df1b7b812ac0118#35)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3915)
```

Please read http://htmlunit.sourceforge.net/submittingJSBugs.html

**Comment by suziying** [comment] 2016-12-27 22:44
Thanks @asashour , but i still don't get it I am using JAVA and why i got JS error ? For the error I posted above, I don't understand what's the meaning of "Returned node was not a DOM element"

**Comment by rbri** [comment] 2017-11-21 17:31
Have added some details to the output, just in case someone is able to reproduce this.

**Comment by rbri** [comment] 2019-08-18 14:34
No new since ages, will close this.

**Closed by rbri** 2019-08-18 14:34 UTC
